services:
  - type: web
    name: cymor-movie-api
    runtime: node
    plan: free

    buildCommand: npm install

    startCommand: npm start

    autoDeploy: true

    healthCheckPath: /health

    envVars:
      - key: NODE_ENV
        value: production

      - key: PORT
        value: 10000

      - key: CACHE_ENABLED
        value: true

      - key: CACHE_TTL
        value: 600
